// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SDHRM.Data;

#nullable disable

namespace SDHRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SDHRM.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SDHRM.Models.BangCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaTotNghiep")
                        .HasColumnType("bit");

                    b.Property<int?>("DenNam")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhanBang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TuNam")
                        .HasColumnType("int");

                    b.Property<string>("XepLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.ToTable("BangCaps");
                });

            modelBuilder.Entity("SDHRM.Models.BangChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CachTinhCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBangChamCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViTriApDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BangChamCongs");
                });

            modelBuilder.Entity("SDHRM.Models.BangChamCongNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangChamCongId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<double>("TongCongHuongLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongCongKhongLuong")
                        .HasColumnType("float");

                    b.Property<double>("TongCongLeTet")
                        .HasColumnType("float");

                    b.Property<double>("TongCongNghiPhep")
                        .HasColumnType("float");

                    b.Property<double>("TongCongThucTe")
                        .HasColumnType("float");

                    b.Property<double>("TongGioTangCa")
                        .HasColumnType("float");

                    b.Property<int>("TongPhutDiMuonVeSom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BangChamCongId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("BangChamCongNhanViens");
                });

            modelBuilder.Entity("SDHRM.Models.CauHinhWifi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVanPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenWifi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CauHinhWifis");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietChamCongNgay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BangChamCongNhanVienId")
                        .HasColumnType("int");

                    b.Property<double>("GioOT")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<string>("KyHieuChamCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhutDiMuon")
                        .HasColumnType("int");

                    b.Property<int>("PhutVeSom")
                        .HasColumnType("int");

                    b.Property<double>("SoCongGhiNhan")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BangChamCongNhanVienId");

                    b.ToTable("ChiTietChamCongNgays");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietKhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("GiaTriKhenThuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KhenThuongId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhenThuongId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("ChiTietKhenThuongs");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietKyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhThucXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KyLuatId")
                        .HasColumnType("int");

                    b.Property<string>("LyDoChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KyLuatId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("ChiTietKyLuats");
                });

            modelBuilder.Entity("SDHRM.Models.ChungChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiemSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("NhomChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChungChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XepLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.ToTable("ChungChis");
                });

            modelBuilder.Entity("SDHRM.Models.CongTy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DaiDienPhapLuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoFax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoGiayPhepDKKD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDayDu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVietTat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CongTys");
                });

            modelBuilder.Entity("SDHRM.Models.DeNghiCapNhatCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuCuaNguoiDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("DeNghiCapNhatCongs");
                });

            modelBuilder.Entity("SDHRM.Models.DonDiMuonVeSom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChuCuaNguoiDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDangKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("SoPhut")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("DonDiMuonVeSoms");
                });

            modelBuilder.Entity("SDHRM.Models.DonTangCa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DenGio")
                        .HasColumnType("time");

                    b.Property<string>("GhiChuCuaNguoiDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoTangCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTangCa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<double>("SoGio")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TuGio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("DonTangCas");
                });

            modelBuilder.Entity("SDHRM.Models.DonXinNghi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuCuaNguoiDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiNghiPhepId")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<double>("SoNgayNghi")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoaiNghiPhepId");

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NhanSuId");

                    b.ToTable("DonXinNghis");
                });

            modelBuilder.Entity("SDHRM.Models.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucDanhNguoiDaiDien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("LuongCoBan")
                        .HasColumnType("float");

                    b.Property<double?>("LuongDongBaoHiem")
                        .HasColumnType("float");

                    b.Property<DateTime>("NgayCoHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDaiDienId")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiHanHopDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TyLeHuongLuong")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDaiDienId");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("HopDongs");
                });

            modelBuilder.Entity("SDHRM.Models.KhenThuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanCu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapKhenThuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiTietDoiTuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucDanhNguoiQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuongKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucKhenThuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiQuyetDinhId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDotKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongGiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiQuyetDinhId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("KhenThuongs");
                });

            modelBuilder.Entity("SDHRM.Models.KinhNghiemLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiDoiChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("NoiLamViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTriCongViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.ToTable("KinhNghiemLamViecs");
                });

            modelBuilder.Entity("SDHRM.Models.KyLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiKyLuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXayRa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiXayRa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("TenKyLuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TongGiaTriThietHai")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.ToTable("KyLuats");
                });

            modelBuilder.Entity("SDHRM.Models.LichSuChamCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhChamCong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiChamCong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianCham")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.ToTable("LichSuChamCongs");
                });

            modelBuilder.Entity("SDHRM.Models.LoaiNghiPhep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CoHuongLuong")
                        .HasColumnType("bit");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TruVaoQuyPhep")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LoaiNghiPheps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoHuongLuong = true,
                            KichHoat = true,
                            TenLoai = "Nghỉ phép năm",
                            TruVaoQuyPhep = true
                        },
                        new
                        {
                            Id = 2,
                            CoHuongLuong = false,
                            KichHoat = true,
                            TenLoai = "Nghỉ không lương",
                            TruVaoQuyPhep = false
                        },
                        new
                        {
                            Id = 3,
                            CoHuongLuong = true,
                            KichHoat = true,
                            TenLoai = "Nghỉ ốm hưởng BHXH",
                            TruVaoQuyPhep = false
                        },
                        new
                        {
                            Id = 4,
                            CoHuongLuong = true,
                            KichHoat = true,
                            TenLoai = "Nghỉ thai sản",
                            TruVaoQuyPhep = false
                        },
                        new
                        {
                            Id = 5,
                            CoHuongLuong = true,
                            KichHoat = true,
                            TenLoai = "Nghỉ bù",
                            TruVaoQuyPhep = false
                        },
                        new
                        {
                            Id = 6,
                            CoHuongLuong = true,
                            KichHoat = true,
                            TenLoai = "Nghỉ kết hôn/ma chay",
                            TruVaoQuyPhep = false
                        });
                });

            modelBuilder.Entity("SDHRM.Models.NhanSu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDinhDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int?>("QuanLyId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViTriCongViecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("QuanLyId");

                    b.HasIndex("UserId");

                    b.HasIndex("ViTriCongViecId");

                    b.ToTable("NhanSus");
                });

            modelBuilder.Entity("SDHRM.Models.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IDTruongPhong")
                        .HasColumnType("int");

                    b.Property<string>("KyHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IDTruongPhong");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaDiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThucHien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomPhucLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuongTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TienCongTyHoTroMoiNguoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienNVDongMoiNguoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongChiPhiMoiNguoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienCongTyHoTro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienNVDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhucLois");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoiChiPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhucLoiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhoanChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhucLoiId");

                    b.ToTable("PhucLoiChiPhis");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoiNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("PhucLoiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhucLoiId");

                    b.ToTable("PhucLoiNhanViens");
                });

            modelBuilder.Entity("SDHRM.Models.QuaTrinhCongTac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<int?>("QuanLyTrucTiepId")
                        .HasColumnType("int");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhChatLaoDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViTriCongViecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("QuanLyTrucTiepId");

                    b.HasIndex("ViTriCongViecId");

                    b.ToTable("QuaTrinhCongTacs");
                });

            modelBuilder.Entity("SDHRM.Models.QuyPhepNhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<double>("PhepThamNien")
                        .HasColumnType("float");

                    b.Property<double>("PhepThuong")
                        .HasColumnType("float");

                    b.Property<double>("PhepTonNamTruoc")
                        .HasColumnType("float");

                    b.Property<double>("SoPhepDaDung")
                        .HasColumnType("float");

                    b.Property<double>("TongPhepNam")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId");

                    b.ToTable("QuyPhepNhanViens");
                });

            modelBuilder.Entity("SDHRM.Models.ThanhPhanLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GiaTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("KieuGiaTri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThanhPhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaThanhPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenThanhPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThanhPhanLuongs");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinChung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenNganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamTotNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapGiayTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapHoChieu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanGiayTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHetHanHoChieu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguyenQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("NoiCapGiayTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiCapHoChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoHoChieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangHonNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoDaoTao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoHocVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XepLoaiTotNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId")
                        .IsUnique();

                    b.ToTable("ThongTinChungs");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaChamCong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayChinhThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHocViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNghiHuuDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThuViec")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.Property<string>("ThamNien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhChatLaoDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiLaoDong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId")
                        .IsUnique();

                    b.ToTable("ThongTinCongViecs");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinLienHe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DTCoQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTLienHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTNhaRieng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiLienHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiTamTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCoQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailLienHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTLienHeKhanCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkMangXaHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanSuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhanSuId")
                        .IsUnique();

                    b.ToTable("ThongTinLienHes");
                });

            modelBuilder.Entity("SDHRM.Models.ViTriCongViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NhomCongViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ViTriCongViecs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SDHRM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SDHRM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SDHRM.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SDHRM.Models.BangCap", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("BangCaps")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.BangChamCongNhanVien", b =>
                {
                    b.HasOne("SDHRM.Models.BangChamCong", "BangChamCong")
                        .WithMany()
                        .HasForeignKey("BangChamCongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangChamCong");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietChamCongNgay", b =>
                {
                    b.HasOne("SDHRM.Models.BangChamCongNhanVien", "BangChamCongNhanVien")
                        .WithMany("ChiTietNgays")
                        .HasForeignKey("BangChamCongNhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangChamCongNhanVien");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietKhenThuong", b =>
                {
                    b.HasOne("SDHRM.Models.KhenThuong", "KhenThuong")
                        .WithMany("ChiTietKhenThuongs")
                        .HasForeignKey("KhenThuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("ChiTietKhenThuongs")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhenThuong");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ChiTietKyLuat", b =>
                {
                    b.HasOne("SDHRM.Models.KyLuat", "KyLuat")
                        .WithMany("ChiTietKyLuats")
                        .HasForeignKey("KyLuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("ChiTietKyLuats")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyLuat");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ChungChi", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("ChungChis")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.DeNghiCapNhatCong", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.DonDiMuonVeSom", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.DonTangCa", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.DonXinNghi", b =>
                {
                    b.HasOne("SDHRM.Models.LoaiNghiPhep", "LoaiNghiPhep")
                        .WithMany("DanhSachDonXinNghi")
                        .HasForeignKey("LoaiNghiPhepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId");

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiNghiPhep");

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.HopDong", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NguoiDaiDien")
                        .WithMany()
                        .HasForeignKey("NguoiDaiDienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDaiDien");

                    b.Navigation("NhanSu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("SDHRM.Models.KhenThuong", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NguoiQuyetDinh")
                        .WithMany()
                        .HasForeignKey("NguoiQuyetDinhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDHRM.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiQuyetDinh");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("SDHRM.Models.KinhNghiemLamViec", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("KinhNghiemLamViecs")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.KyLuat", b =>
                {
                    b.HasOne("SDHRM.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("SDHRM.Models.LichSuChamCong", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.NhanSu", b =>
                {
                    b.HasOne("SDHRM.Models.PhongBan", "PhongBan")
                        .WithMany("NhanSus")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "QuanLy")
                        .WithMany()
                        .HasForeignKey("QuanLyId");

                    b.HasOne("SDHRM.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("SDHRM.Models.ViTriCongViec", "ViTriCongViec")
                        .WithMany()
                        .HasForeignKey("ViTriCongViecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("QuanLy");

                    b.Navigation("User");

                    b.Navigation("ViTriCongViec");
                });

            modelBuilder.Entity("SDHRM.Models.PhongBan", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "TruongPhong")
                        .WithMany()
                        .HasForeignKey("IDTruongPhong");

                    b.Navigation("TruongPhong");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoiChiPhi", b =>
                {
                    b.HasOne("SDHRM.Models.PhucLoi", "PhucLoi")
                        .WithMany("PhucLoiChiPhis")
                        .HasForeignKey("PhucLoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhucLoi");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoiNhanVien", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.PhucLoi", "PhucLoi")
                        .WithMany("PhucLoiNhanViens")
                        .HasForeignKey("PhucLoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");

                    b.Navigation("PhucLoi");
                });

            modelBuilder.Entity("SDHRM.Models.QuaTrinhCongTac", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany("QuaTrinhCongTacs")
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SDHRM.Models.NhanSu", "QuanLyTrucTiep")
                        .WithMany()
                        .HasForeignKey("QuanLyTrucTiepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SDHRM.Models.ViTriCongViec", "ViTriCongViec")
                        .WithMany()
                        .HasForeignKey("ViTriCongViecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanSu");

                    b.Navigation("PhongBan");

                    b.Navigation("QuanLyTrucTiep");

                    b.Navigation("ViTriCongViec");
                });

            modelBuilder.Entity("SDHRM.Models.QuyPhepNhanVien", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithMany()
                        .HasForeignKey("NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinChung", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithOne("ThongTinChung")
                        .HasForeignKey("SDHRM.Models.ThongTinChung", "NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinCongViec", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithOne("ThongTinCongViec")
                        .HasForeignKey("SDHRM.Models.ThongTinCongViec", "NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.ThongTinLienHe", b =>
                {
                    b.HasOne("SDHRM.Models.NhanSu", "NhanSu")
                        .WithOne("ThongTinLienHe")
                        .HasForeignKey("SDHRM.Models.ThongTinLienHe", "NhanSuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SDHRM.Models.BangChamCongNhanVien", b =>
                {
                    b.Navigation("ChiTietNgays");
                });

            modelBuilder.Entity("SDHRM.Models.KhenThuong", b =>
                {
                    b.Navigation("ChiTietKhenThuongs");
                });

            modelBuilder.Entity("SDHRM.Models.KyLuat", b =>
                {
                    b.Navigation("ChiTietKyLuats");
                });

            modelBuilder.Entity("SDHRM.Models.LoaiNghiPhep", b =>
                {
                    b.Navigation("DanhSachDonXinNghi");
                });

            modelBuilder.Entity("SDHRM.Models.NhanSu", b =>
                {
                    b.Navigation("BangCaps");

                    b.Navigation("ChiTietKhenThuongs");

                    b.Navigation("ChiTietKyLuats");

                    b.Navigation("ChungChis");

                    b.Navigation("KinhNghiemLamViecs");

                    b.Navigation("QuaTrinhCongTacs");

                    b.Navigation("ThongTinChung");

                    b.Navigation("ThongTinCongViec");

                    b.Navigation("ThongTinLienHe");
                });

            modelBuilder.Entity("SDHRM.Models.PhongBan", b =>
                {
                    b.Navigation("NhanSus");
                });

            modelBuilder.Entity("SDHRM.Models.PhucLoi", b =>
                {
                    b.Navigation("PhucLoiChiPhis");

                    b.Navigation("PhucLoiNhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
